import { WeddingData } from './types';

export const DEMO_WEDDINGS: WeddingData[] = [
  {
    id: 'w-001',
    slug: 'reeha-ahamed',
    status: 'published',
    createdAt: '2026-09-01T10:00:00.000Z',
    packageTier: 'luxury',
    theme: 'romantic-red',
    language: 'en',
    darkMode: true,
    couple: {
      brideName: 'Reeha',
      groomName: 'Ahamed',
      bridePhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
      groomPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
      couplePhoto: '/couple_flower_back_pose.png',
      brideBio: 'A creative interior designer with a passion for art, travel, and warm smiles. Reeha brings joy to every room she enters.',
      groomBio: 'A soft-spoken software architect who loves classical music, photography, and late-night star gazing with Reeha.',
      brideParents: 'Daughter of Mr. Mahinda Perera & Mrs. Chitra Perera',
      groomParents: 'Son of Mr. Sunil Fernando & Mrs. Rohini Fernando',
      weddingDate: '2026-12-13',
      weddingTime: '04:30 PM',
      locationName: 'Lee Meredian Hall, Sainthamaruthu',
      venueAddress: 'Main Street, Sainthamaruthu, Sri Lanka',
      googleMapsUrl: 'https://maps.google.com/?q=Lee+Meredian+Hall+Sainthamaruthu',
      invitationMessage: 'Together with our families, we request the honor of your presence as we celebrate our love and begin our new journey together.',
      brideWhatsApp: '94752123521',
      groomWhatsApp: '94777654321',
    },
    music: {
      title: '',
      url: '',
      enabled: false,
    },
    effects: {
      rosePetals: false,
      cherryBlossoms: false,
      hearts: false,
      sparkles: true,
      confetti: true,
    },
    interactiveFeatures: {
      scratchCard: true,
      eraseCard: true,
      tapFlowers: true,
      surpriseGift: true,
      candle: true,
      heartCounter: true,
    },
    events: [
      {
        id: 'e-1',
        title: 'Engagement & Ring Ceremony',
        date: '2026-11-25',
        time: '05:00 PM',
        venue: 'Lotus Hall, Cinnamon Grand Colombo',
        description: 'An intimate evening gathering of family and close friends to exchange rings and celebrate the beginning of our wedding festivities.',
      },
      {
        id: 'e-2',
        title: 'Traditional Poruwa & Holy Blessing',
        date: '2026-11-26',
        time: '04:30 PM',
        venue: 'Grand Ballroom, Shangri-La Colombo',
        description: 'The sacred wedding ceremony featuring traditional customs, chanting of Jayamangala Gatha, and lighting of the ceremonial oil lamp.',
      },
      {
        id: 'e-3',
        title: 'Dinner & Evening Reception',
        date: '2026-11-26',
        time: '07:30 PM',
        venue: 'Grand Ballroom & Terrace, Shangri-La Colombo',
        description: 'Join us for a magical evening of live music, delicious dinner buffet, cake cutting, toasts, and dancing under the stars.',
      },
    ],
    loveStory: [
      {
        id: 's-1',
        year: '2019',
        title: 'First Meeting at University',
        description: 'We bumped into each other at the university library during finals week over a spilled cup of coffee.',
        image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 's-2',
        year: '2021',
        title: 'Our First Official Date',
        description: 'A cozy sunset dinner by the beach in Galle, talking for hours until the stars came out.',
        image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 's-3',
        year: '2024',
        title: 'The Magical Proposal',
        description: 'Ahan surprised Nethmi on a hill country tea estate trip in Ella under a canopy of fairy lights.',
        image: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 's-4',
        year: '2026',
        title: 'Our Big Day',
        description: 'Stepping into forever hand in hand, surrounded by the warmth and love of our favorite people.',
        image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
      },
    ],
    family: [
      { id: 'f-1', title: 'Bride\'s Parents', names: 'Mr. Mahinda Perera & Mrs. Chitra Perera', relation: 'Parents of the Bride' },
      { id: 'f-2', title: 'Groom\'s Parents', names: 'Mr. Sunil Fernando & Mrs. Rohini Fernando', relation: 'Parents of the Groom' },
      { id: 'f-3', title: 'Maid of Honor', names: 'Kavindi Perera', relation: 'Sister of the Bride' },
      { id: 'f-4', title: 'Best Man', names: 'Dinesh Fernando', relation: 'Brother of the Groom' },
    ],
    gallery: [
      { id: 'g-1', url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80', caption: 'Pre-wedding sunset session in Galle', category: 'prewedding' },
      { id: 'g-2', url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80', caption: 'Engagement celebration smiles', category: 'engagement' },
      { id: 'g-3', url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80', caption: 'Walking by the shore', category: 'couple' },
      { id: 'g-4', url: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=800&q=80', caption: 'Family blessing moment', category: 'family' },
      { id: 'g-5', url: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80', caption: 'Laughter and joy', category: 'couple' },
      { id: 'g-6', url: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=800&q=80', caption: 'Childhood memory', category: 'childhood' },
    ],
    program: [
      { id: 'p-1', time: '04:30 PM', event: 'Guest Arrival & Welcome Refreshments' },
      { id: 'p-2', time: '05:00 PM', event: 'Traditional Poruwa Ceremony' },
      { id: 'p-3', time: '06:15 PM', event: 'Group Photographs & Cocktail Hour' },
      { id: 'p-4', time: '07:30 PM', event: 'Grand Entrance & Champagne Toast' },
      { id: 'p-5', time: '08:00 PM', event: 'Gourmet Dinner Buffet' },
      { id: 'p-6', time: '09:00 PM', event: 'First Dance & Celebration Party' },
    ],
    dressCode: {
      gentlemen: 'Formal Suit, Tuxedo or Traditional National Attire',
      ladies: 'Elegant Saree, Evening Gown or Formal Dress',
      note: 'We kindly request guests to avoid wearing solid white or cream.',
    },
    menu: [
      { category: 'Starters', items: ['Smoked Salmon Crostini', 'Mini Truffle Quiche', 'Spiced Prawn Shooters'] },
      { category: 'Main Dishes', items: ['Saffron Basmati Rice', 'Roast Lamb with Rosemary Sauce', 'Butter Chicken Curry', 'Grilled Tiger Prawns'] },
      { category: 'Desserts & Beverages', items: ['Tropical Fruit Pavlova', 'Dark Chocolate Mousse Cups', 'Fine Wine & Signature Cocktails'] },
    ],
    rsvpSettings: {
      enabled: true,
      deadline: '2026-11-10',
      allowFoodPreference: true,
      foodOptions: ['Chicken / Meat', 'Seafood Delight', 'Vegetarian / Vegan', 'Halal'],
    },
    wishesEnabled: true,
    rsvps: [
      { id: 'r-1', guestName: 'Rohan Jayasinghe', count: 2, attending: true, foodPreference: 'Seafood Delight', message: 'Can\'t wait to celebrate with you both!', date: '2026-09-10' },
      { id: 'r-2', guestName: 'Anusha De Silva', count: 1, attending: true, foodPreference: 'Vegetarian / Vegan', message: 'Wishing you endless love and happiness!', date: '2026-09-12' },
    ],
    guestWishes: [
      { id: 'w-1', guestName: 'Dilshan & Sarala', message: 'Congratulations Reeha & Ahamed! Wishing you both a lifetime of love, laughter, and beautiful memories!', reaction: '❤️ Congratulations', approved: true, createdAt: '2026-09-05' },
      { id: 'w-2', guestName: 'Aunty Malini', message: 'May God bless your union with happiness and prosperity always.', reaction: '💍 Best Wishes', approved: true, createdAt: '2026-09-08' },
    ],
    heartCount: 0,
  },
  {
    id: 'w-002',
    slug: 'ashan-nethmi',
    status: 'published',
    createdAt: '2026-09-05T12:00:00.000Z',
    packageTier: 'premium',
    theme: 'luxury-gold',
    language: 'en',
    darkMode: true,
    couple: {
      brideName: 'Nethmi Fonseka',
      groomName: 'Ashan Wickramasinghe',
      bridePhoto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
      groomPhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
      couplePhoto: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
      brideBio: 'Passionate doctor and nature lover who finds peace in music and books.',
      groomBio: 'Financial analyst with an adventurous spirit and love for sports.',
      brideParents: 'Daughter of Dr. & Mrs. Fonseka',
      groomParents: 'Son of Mr. & Mrs. Wickramasinghe',
      weddingDate: '2026-12-12',
      weddingTime: '06:00 PM',
      locationName: 'The Kingsbury Ballroom, Colombo',
      venueAddress: '48 Janadhipathi Mawatha, Colombo 00100',
      googleMapsUrl: 'https://maps.google.com/?q=The+Kingsbury+Colombo',
      invitationMessage: 'We request the pleasure of your company as we tie the knot!',
      brideWhatsApp: '94770000001',
      groomWhatsApp: '94770000002',
    },
    music: {
      title: '',
      url: '',
      enabled: false,
    },
    effects: {
      rosePetals: false,
      cherryBlossoms: true,
      hearts: true,
      sparkles: true,
      confetti: true,
    },
    interactiveFeatures: {
      scratchCard: true,
      eraseCard: true,
      tapFlowers: true,
      surpriseGift: true,
      candle: true,
      heartCounter: true,
    },
    events: [
      {
        id: 'e-201',
        title: 'Wedding Reception',
        date: '2026-12-12',
        time: '06:00 PM',
        venue: 'The Kingsbury Ballroom',
        description: 'Celebration dinner and evening dance.',
      },
    ],
    loveStory: [
      { id: 'ls-1', year: '2020', title: 'Met in Kandy', description: 'Met during a weekend getaway.' },
      { id: 'ls-2', year: '2025', title: 'Engaged', description: 'Said YES under the stars.' },
    ],
    family: [],
    gallery: [
      { id: 'g-201', url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80', caption: 'Together forever', category: 'couple' },
    ],
    program: [],
    dressCode: { gentlemen: 'Black Tie / Suit', ladies: 'Evening Gown' },
    menu: [],
    rsvpSettings: { enabled: true, deadline: '2026-12-01', allowFoodPreference: false, foodOptions: [] },
    wishesEnabled: true,
    rsvps: [],
    guestWishes: [],
    heartCount: 18,
  },
];
