import { ThemeId } from './types';

export interface ThemeConfig {
  id: ThemeId;
  name: string;
  description: string;
  bgGradient: string;
  cardBg: string;
  cardBorder: string;
  textPrimary: string;
  textSecondary: string;
  accent: string;
  accentHover: string;
  badgeBg: string;
  badgeText: string;
  fontFamily: string;
  heroOverlay: string;
  envelopeBg: string;
  envelopeFlap: string;
  particleColor: string;
}

export const THEMES: Record<ThemeId, ThemeConfig> = {
  'romantic-red': {
    id: 'romantic-red',
    name: 'Royal Champagne',
    description: 'Warm champagne parchment, metallic gold filigree, and royal palace elegance',
    bgGradient: 'from-[#FAF6EE] via-[#F3EAD9] to-[#E9DCC7]',
    cardBg: 'bg-[#FAF6F0]/90 backdrop-blur-md',
    cardBorder: 'border-[#D4AF37]/50',
    textPrimary: 'text-[#3E2B1E]',
    textSecondary: 'text-[#7C624E]',
    accent: 'bg-gradient-to-r from-[#D4AF37] via-[#F3E5AB] to-[#B8860B]',
    accentHover: 'hover:from-[#B8860B] hover:to-[#D4AF37]',
    badgeBg: 'bg-[#D4AF37]/20',
    badgeText: 'text-[#5C4332] border-[#D4AF37]/50',
    fontFamily: 'font-serif',
    heroOverlay: 'bg-gradient-to-t from-[#FAF6EE] via-[#FAF6EE]/60 to-transparent',
    envelopeBg: 'from-[#F5EBDC] to-[#E4D5C0]',
    envelopeFlap: 'from-[#FAF2E6] to-[#EADBC5]',
    particleColor: '#D4AF37',
  },
  'elegant-pink': {
    id: 'elegant-pink',
    name: 'Blush Rose Gold',
    description: 'Luxury blush rose, champagne gold, and soft velvet for a romantic aesthetic',
    bgGradient: 'from-rose-950 via-stone-950 to-rose-950',
    cardBg: 'bg-stone-900/70 backdrop-blur-md',
    cardBorder: 'border-rose-400/40',
    textPrimary: 'text-rose-100',
    textSecondary: 'text-amber-200/90',
    accent: 'bg-gradient-to-r from-rose-400 via-amber-400 to-rose-500',
    accentHover: 'hover:from-rose-500 hover:to-amber-500',
    badgeBg: 'bg-rose-400/20',
    badgeText: 'text-rose-200 border-rose-300/40',
    fontFamily: 'font-serif',
    heroOverlay: 'bg-gradient-to-t from-rose-950 via-rose-950/70 to-transparent',
    envelopeBg: 'from-rose-900 to-stone-950',
    envelopeFlap: 'from-rose-800 to-stone-900',
    particleColor: '#E8B4B8',
  },
  'royal-purple': {
    id: 'royal-purple',
    name: 'Royal Purple',
    description: 'Majestic violet, deep plum, and glittering champagne gold',
    bgGradient: 'from-slate-950 via-purple-950 to-slate-950',
    cardBg: 'bg-purple-950/60 backdrop-blur-md',
    cardBorder: 'border-purple-400/30',
    textPrimary: 'text-purple-50',
    textSecondary: 'text-purple-200',
    accent: 'bg-gradient-to-r from-purple-500 to-indigo-600',
    accentHover: 'hover:from-purple-600 hover:to-indigo-700',
    badgeBg: 'bg-purple-500/20',
    badgeText: 'text-purple-200 border-purple-400/40',
    fontFamily: 'font-serif',
    heroOverlay: 'bg-gradient-to-t from-purple-950 via-purple-950/70 to-transparent',
    envelopeBg: 'from-purple-900 to-slate-950',
    envelopeFlap: 'from-purple-800 to-slate-900',
    particleColor: '#A855F7',
  },
  'royal-blue': {
    id: 'royal-blue',
    name: 'Royal Blue',
    description: 'Sapphire blue, navy velvet, and crisp silver shimmer',
    bgGradient: 'from-slate-950 via-blue-950 to-slate-950',
    cardBg: 'bg-blue-950/60 backdrop-blur-md',
    cardBorder: 'border-blue-400/30',
    textPrimary: 'text-blue-50',
    textSecondary: 'text-blue-200',
    accent: 'bg-gradient-to-r from-blue-500 to-sky-600',
    accentHover: 'hover:from-blue-600 hover:to-sky-700',
    badgeBg: 'bg-blue-500/20',
    badgeText: 'text-blue-200 border-blue-400/40',
    fontFamily: 'font-serif',
    heroOverlay: 'bg-gradient-to-t from-blue-950 via-blue-950/70 to-transparent',
    envelopeBg: 'from-blue-900 to-slate-950',
    envelopeFlap: 'from-blue-800 to-slate-900',
    particleColor: '#3B82F6',
  },
  'luxury-gold': {
    id: 'luxury-gold',
    name: 'Luxury Gold',
    description: 'Rich metallic gold, warm amber, and deep dark charcoal',
    bgGradient: 'from-stone-950 via-amber-950/80 to-stone-950',
    cardBg: 'bg-amber-950/50 backdrop-blur-md',
    cardBorder: 'border-amber-400/40',
    textPrimary: 'text-amber-100',
    textSecondary: 'text-amber-200/80',
    accent: 'bg-gradient-to-r from-amber-400 via-yellow-500 to-amber-600',
    accentHover: 'hover:from-amber-500 hover:to-amber-700',
    badgeBg: 'bg-amber-400/20',
    badgeText: 'text-amber-200 border-amber-400/40',
    fontFamily: 'font-serif',
    heroOverlay: 'bg-gradient-to-t from-stone-950 via-stone-950/70 to-transparent',
    envelopeBg: 'from-amber-900 to-stone-950',
    envelopeFlap: 'from-amber-800 to-stone-900',
    particleColor: '#F59E0B',
  },
  'elegant-white': {
    id: 'elegant-white',
    name: 'Elegant White',
    description: 'Crisp pearl white, champagne accents, and soft minimalist luxury',
    bgGradient: 'from-stone-900 via-zinc-900 to-stone-900',
    cardBg: 'bg-stone-900/80 backdrop-blur-md',
    cardBorder: 'border-amber-200/30',
    textPrimary: 'text-stone-100',
    textSecondary: 'text-stone-300',
    accent: 'bg-gradient-to-r from-amber-300 to-yellow-500',
    accentHover: 'hover:from-amber-400 hover:to-yellow-600',
    badgeBg: 'bg-amber-200/10',
    badgeText: 'text-amber-200 border-amber-200/30',
    fontFamily: 'font-serif',
    heroOverlay: 'bg-gradient-to-t from-stone-950 via-stone-950/70 to-transparent',
    envelopeBg: 'from-stone-800 to-stone-950',
    envelopeFlap: 'from-stone-700 to-stone-900',
    particleColor: '#FDE68A',
  },
  'black-luxury': {
    id: 'black-luxury',
    name: 'Black Luxury',
    description: 'Midnight black glassmorphism with glowing gold accents',
    bgGradient: 'from-black via-zinc-950 to-black',
    cardBg: 'bg-zinc-900/70 backdrop-blur-md',
    cardBorder: 'border-yellow-500/40',
    textPrimary: 'text-white',
    textSecondary: 'text-zinc-300',
    accent: 'bg-gradient-to-r from-yellow-400 via-amber-500 to-yellow-600',
    accentHover: 'hover:from-yellow-500 hover:to-amber-600',
    badgeBg: 'bg-yellow-500/20',
    badgeText: 'text-yellow-300 border-yellow-500/40',
    fontFamily: 'font-serif',
    heroOverlay: 'bg-gradient-to-t from-black via-black/80 to-transparent',
    envelopeBg: 'from-zinc-900 to-black',
    envelopeFlap: 'from-zinc-800 to-zinc-950',
    particleColor: '#EAB308',
  },
  'floral': {
    id: 'floral',
    name: 'Floral Romance',
    description: 'Botanical rose, soft sage, and wild blossom highlights',
    bgGradient: 'from-stone-950 via-rose-950 to-emerald-950',
    cardBg: 'bg-rose-950/50 backdrop-blur-md',
    cardBorder: 'border-emerald-400/30',
    textPrimary: 'text-rose-100',
    textSecondary: 'text-emerald-200',
    accent: 'bg-gradient-to-r from-rose-400 to-emerald-500',
    accentHover: 'hover:from-rose-500 hover:to-emerald-600',
    badgeBg: 'bg-emerald-400/20',
    badgeText: 'text-emerald-200 border-emerald-400/40',
    fontFamily: 'font-serif',
    heroOverlay: 'bg-gradient-to-t from-stone-950 via-stone-950/70 to-transparent',
    envelopeBg: 'from-rose-900 to-emerald-950',
    envelopeFlap: 'from-rose-800 to-emerald-900',
    particleColor: '#FB7185',
  },
  'green-garden': {
    id: 'green-garden',
    name: 'Green Garden',
    description: 'Emerald green, gold leaf, and lush botanical foliage',
    bgGradient: 'from-emerald-950 via-teal-950 to-stone-950',
    cardBg: 'bg-emerald-950/60 backdrop-blur-md',
    cardBorder: 'border-emerald-400/40',
    textPrimary: 'text-emerald-50',
    textSecondary: 'text-emerald-200',
    accent: 'bg-gradient-to-r from-emerald-500 to-teal-600',
    accentHover: 'hover:from-emerald-600 hover:to-teal-700',
    badgeBg: 'bg-emerald-500/20',
    badgeText: 'text-emerald-200 border-emerald-400/40',
    fontFamily: 'font-serif',
    heroOverlay: 'bg-gradient-to-t from-emerald-950 via-emerald-950/70 to-transparent',
    envelopeBg: 'from-emerald-900 to-stone-950',
    envelopeFlap: 'from-emerald-800 to-stone-900',
    particleColor: '#10B981',
  },
  'traditional': {
    id: 'traditional',
    name: 'Traditional Royal',
    description: 'Maroon velvet, vibrant gold, turmeric amber, and royal motifs',
    bgGradient: 'from-red-950 via-amber-950 to-red-950',
    cardBg: 'bg-red-950/60 backdrop-blur-md',
    cardBorder: 'border-amber-400/50',
    textPrimary: 'text-amber-50',
    textSecondary: 'text-amber-200',
    accent: 'bg-gradient-to-r from-amber-400 to-red-600',
    accentHover: 'hover:from-amber-500 hover:to-red-700',
    badgeBg: 'bg-amber-500/20',
    badgeText: 'text-amber-300 border-amber-400/50',
    fontFamily: 'font-serif',
    heroOverlay: 'bg-gradient-to-t from-red-950 via-red-950/70 to-transparent',
    envelopeBg: 'from-red-900 to-amber-950',
    envelopeFlap: 'from-red-800 to-amber-900',
    particleColor: '#F59E0B',
  },
};
